insert into i72lumav.albumes (id_album, titulo, duracion, ano, n_canciones, tipo, descripcion) values (1, 'Dire Straits', '41 minutos', 1978, 9, 'LP', 'Dire Straits es el album homonimo de la banda britanica Dire Straits, lanzado en 1978. Marca el debut de la banda en el mundo musical y uno de los mayores exitos del grupo con el sencillo -Sultans of Swing-.??\nElaborado a partir de una serie de maquetas que el grupo habia conseguido grabar de su propio bolsillo, incorporaba practicamente todo el repertorio de la banda. Excluidos del album quedaron -Move It Away-, -Real Girl-, -Me and My Friends- y una version del tema de Chuck Berry -Nadine-. Durante la promocion del album, la banda interpretaria la cancion -What s The Matter, Baby?-, escrita conjuntamente por Mark y David Knopfler, y posteriormente publicada en el album de 1995 Live at the BBC.?\nLa imagen de la portada esta extraida de una pintura de Chuck Loyola.\nDire Straits fue remasterizado y reeditado junto al resto del catalogo musical de Dire Straits el 19 de septiembre de 2000.?');
insert into i72lumav.albumes (id_album, titulo, duracion, ano, n_canciones, tipo, descripcion) values (2, 'Communique', '42 minutos', 1979, 9, 'LP', 'Communique es el segundo album de la banda britanica Dire Straits, lanzado en 1979.\nLas sesiones de grabacion de Communique tuvieron un rapido desarrollo tras el exito del sencillo -Sultans of Swing-, extraido del album Dire Straits. Para ello, se emplearon maquetas que el grupo tenia grabadas de anteriores sesiones. Barry Beckett, productor del album, estaba convencido de que la falta de teclados habia dotado al album anterior de un sonido duro y de una produccion pobre, de modo que decidio colaborar como teclista en algunas canciones aunque firmando con el pseudonimo B. Bear.\nDurante la grabacion de Communique, el grupo coincidio con Bob Dylan debido al trabajo de Beckett en el album Slow Train Coming. Mark Knopfler y Pick Withers se unirian al equipo de Dylan en la grabacion de algunos temas del disco.\nDurante los conciertos, la banda interpreto dos canciones que jamas fueron publicadas: -In My Car- y -Bernadette-, compuesta esta ultima por David Knopfler.\nCommunique fue remasterizado y reeditado junto al resto del catalogo musical de Dire Straits el 19 de septiembre de 2000.');
insert into i72lumav.albumes (id_album, titulo, duracion, ano, n_canciones, tipo, descripcion) values (3, 'Making Movies', '38 minutos', 1980, 7, 'LP', 'Making Movies es el tercer album de la banda britanica Dire Straits, lanzado en 1980. Figura en el puesto 52 de la lista de los 100 mejores albumes de los 80 elaborada por la revista musical Rolling Stone.\nEl album supone la partida de David Knopfler, sustituido durante la grabacion por Sid McGuinnis. Asimismo, supone el segundo album en el que el grupo incorpora un teclista, posteriormente ligado de forma permanente a la formacion. En Making Movies, el teclista seria Roy Bittan de la E Street Band.\nDurante las sesiones de grabacion serian desechadas dos canciones: -Suicide Towers- y la cancion que da nombre al titulo del album, -Making Movies-, posteriormente introducida como un parrafo en la letra de la cancion -Skateaway-. La produccion corrio a cargo de Jimmy Iovine, productor del album Born To Run de Bruce Springsteen.\nMaking Movies fue remasterizado y reeditado junto al resto del catalogo de Dire Straits el 19 de septiembre de 2000.');
insert into i72lumav.albumes (id_album, titulo, duracion, ano, n_canciones, tipo, descripcion) values (4, 'Journeyman', '56 minutos', 1989, 12, 'LP', 'Journeyman es el undecimo album de estudio del musico britanico Eric Clapton, publicado por la compania discografica Reprise Records en 1989.\nEl album fue anunciado como un retorno a la forma de Clapton, que habia luchado durante mediados de la decada de 1980 con su adiccion al alcohol. Parte del album tiene un sonido electronico influido por la escena del rock de la decada, aunque tambien incluye canciones blues como -Before You Accuse Me-, -Running on Faith- y -Hard Times-. Clapton obtuvo un notable exito con -Bad Love-, que gano el Grammy a la mejor interpretacion vocal de rock masculina y alcanzo el puesto uno en la lista Mainstream Rock Tracks. Otro sencillo, -Pretending-, tambien llego al puesto numero uno el ano anterior, manteniendose en lo mas alto de la lista durante cinco semanas.\nAunque Journeyman obtuvo solo un exito comercial moderado, alcanzando el puesto dieciseis en la lista estadounidense Billboard 200, se convirtio en su primer disco de estudio en alcanzar el estatus de doble platino al vender mas de dos millones de copias en los Estados Unidos. Fue tambien mencionado por el propio musico como uno de sus trabajos favoritos.?');
insert into i72lumav.albumes (id_album, titulo, duracion, ano, n_canciones, tipo, descripcion) values (5, 'ExtendeDancEPlay', '11 minutos y 10 segundos', 1983, 4, 'EP', 'ExtendedancEPlay, tambien conocido como Extended Dance o Twisting by the Pool EP en referencia al primer tema, es un EP de la banda britanica Dire Straits publicado tras su cuarto album de estudio, Love Over Gold. En un intento por volver a la sencillez y al sonido de sus primeros trabajos, el album recoge tres canciones con un estilo mas desenfadado que su antecesor. La sustitucion del bateria Pick Whiters por Terry Williams supuso un apoyo a la hora de modificar el estilo de los temas debido a su anterior presencia en el grupo de musica bailable Rockpile.\nEn su publicacion britanica, el EP contenia tres temas. Para la edicion estadounidense, se anadio la cara B del sencillo -Love Over Gold-, -Badges, Posters, Stickers and T-Shirts-.');
insert into i72lumav.albumes (id_album, titulo, duracion, ano, n_canciones, tipo, descripcion) values (6, 'August', '56 minutos', 1986, 12, 'LP', 'August es el decimo album de estudio del musico britanico Eric Clapton, publicado por la compania discografica Warner Bros. Records en noviembre de 1986. Producido por Phil Collins y Tom Dowd, colaborador habitual de Clapton, supuso uno de los trabajos en solitario del musico mas vendidos hasta la fecha, superado posteriormente por trabajos como Journeyman, Unplugged y From the Cradle.\nPara su grabacion, Clapton conto con el respaldo de una banda formada por Collins en la bateria, el bajista Nathan East, el teclista Greg Phillinganes, el saxofonista Michael Brecker, los trompetistas Randy Brecker y Jon Faddis, y Dave Bargeron al trombon. August incluyo los sencillos -It s in the Way That You Use It-, coescrito con Robbie Robertson e incluido en la banda sonora del largometraje de Martin Scorsese El color del dinero, y -Tearing Us Apart-, un duo con la cantante Tina Turner, que alcanzaron los puestos uno y nueve respectivamente en la lista Mainstream Rock Tracks. August tambien incluyo -Holy Mother-, un tributo al teclista de The Band Richard Manuel, fallecido en 1986.');
insert into i72lumav.albumes (id_album, titulo, duracion, ano, n_canciones, tipo, descripcion) values (7, 'Brothers In Arms', '54 minutos', 1985, 9, 'LP', null);
insert into i72lumav.albumes (id_album, titulo, duracion, ano, n_canciones, tipo, descripcion) values (8, 'On Every Street', '1 hora', 1991, 12, 'LP', 'On Every Street es el sexto y ultimo album de la banda britanica Dire Straits, lanzado en 1991. Tras la gira llevada a cabo como promocion del anterior album de estudio, Brothers In Arms, el grupo llevo a cabo la misma formula en la elaboracion de su nuevo disco: un sexteto basico, junto a una larga lista de musicos de estudio que apoyarian en la grabacion. A estas alturas, Dire Straits, lejos de la banda cohesionada que fue en los anos 70, se habia transformado en una marca a traves de la cual Mark Knopfler, rodeado de una serie de musicos que mas o menos colaboraban de forma asidua, publicaba sus canciones. Mark Knopfler se encontraba cansado del estilo que la gente esperaba de Dire Straits tras su exito en los 80 y en este album trato de experimentar con otros estilos como el country o el blues. El album fue recibido con division de opiniones y unas ventas medianas, si bien hasta la fecha se contabilizan en torno a los 8 millones. Esto empujo a Knopfler a lanzar una carrera en solitario al margen de la banda para buscar una mayor libertad artistica.');
insert into i72lumav.albumes (id_album, titulo, duracion, ano, n_canciones, tipo, descripcion) values (9, 'Back To Black', '34 minutos', 2006, 11, 'LP', 'Back to Black es el segundo y ultimo album de estudio de la cantante britanica Amy Winehouse. Su lanzamiento principal fue realizado el 4 de octubre de 2006 en el Reino Unido. Su promocion abarco el lanzamiento de cinco sencillos: -Rehab-, -You Know I m No Good-, -Back to Black-, -Tears Dry on Their Own- y -Love Is a Losing Game-, siendo el primero de ellos el mas exitoso. En el mes de junio de 2007, se convirtio en el n.� 9 en Estados Unidos y, tras ello, vendio 1,7 millones de descargas en el pais, hasta el 23 de julio de 2011.? Back To Black recibio criticas generalmente positivas por parte de los criticos de musica, ganandose el elogio por sus influencias clasicas de soul.\nTras su lanzamiento y promocion, Back to Black vendio mas de 20 millones de copias alrededor del mundo, ? las cuales le convirtieron en el album de mayor exito comercial de Amy Winehouse. De acuerdo al sistema de informacion de ventas Nielsen SoundScan, hasta el 23 de julio de 2011, este vendio alrededor de 2,3 millones de copias en los Estados Unidos, ? con dos millones de ellas certificadas con doble disco de platino por la asociacion de musica RIAA.');
insert into i72lumav.albumes (id_album, titulo, duracion, ano, n_canciones, tipo, descripcion) values (10, 'Stand and Deliver', '4 minutos y 33 segundos', 2020, 1, 'Single', null);
insert into i72lumav.albumes (id_album, titulo, duracion, ano, n_canciones, tipo, descripcion) values (11, 'The Trawlerman s Song EP', '26 minutos', 2005, 6, 'EP', 'The Trawlerman s Song es un EP del musico britanico Mark Knopfler, publicado por la compania discografica Mercury Records en junio de 2005. El EP contiene la version de -The Trawlerman s Song- publicada en el album de 2004 Shangri-La y grabaciones en directo desde el estudio en una sola toma de otras cinco canciones, realizadas en los Shangri-La Studios de Malibu.?');
insert into i72lumav.albumes (id_album, titulo, duracion, ano, n_canciones, tipo, descripcion) values (12, 'Redbud Tree', '3 minutos y 18 segundos', 2012, 1, 'Single', null);
insert into i72lumav.albumes (id_album, titulo, duracion, ano, n_canciones, tipo, descripcion) values (13, '24K Magic', '3 minutos y 25 segundos', 2016, 1, 'Single', null);
insert into i72lumav.albumes (id_album, titulo, duracion, ano, n_canciones, tipo, descripcion) values (14, 'Why Aye Man', '21 minutos', 2002, 4, 'EP', null);
insert into i72lumav.albumes (id_album, titulo, duracion, ano, n_canciones, tipo, descripcion) values (15, 'The Busking CD', '25 minutos y 14 segundo', 2013, 5, 'EP', null);
insert into i72lumav.albumes (id_album, titulo, duracion, ano, n_canciones, tipo, descripcion) values (16, 'I Shot The Sheriff', '6 minutos y 51 segundos', 2018, 1, 'Single', null);
insert into i72lumav.artistas (id_artista, nombre, ranking, descripcion) values (1, 'Dire Straits', 1, 'Dire Straits fue una banda de rock britanica formada en Londres en 1977 por Mark Knopfler, David Knopfler, John Illsley y Pick Withers, estando activos hasta el ano 1995. Dire Straits es uno de los artistas musicales mas vendidos del mundo, con ventas de albumes de mas de 100 millones.?Su primer sencillo, "Sultans of Swing", de su album debut homonimo de 1978, llego a los diez primeros en las listas de exitos del Reino Unido y los Estados Unidos. Le siguieron exitos como "Romeo and Juliet", "Private Investigations", "Twisting by the Pool", "Money for Nothing" y "Walk of Life".? Su album de mayor exito comercial, Brothers in Arms, ha vendido mas de 30 millones de copias; fue el primer album en vender un millon de copias en disco compacto?? y es el octavo album mas vendido en la historia del Reino Unido. Segun el Guinness Book of British Hit Albums, Dire Straits ha pasado mas de 1100 semanas en la lista de albumes del Reino Unido, la quinta mayor cantidad de todos los tiempos.?');
insert into i72lumav.artistas (id_artista, nombre, ranking, descripcion) values (2, 'Eric Clapton', 3, 'Eric Patrick Clapton, mas conocido como Eric Clapton, es un guitarrista, cantante y compositor de rock y blues britanico, conocido por su magistral habilidad con la guitarra electrica, en concreto con su Stratocaster.? Apodado Slowhand, ? desde su epoca en The Yardbirds, y God en su epoca con Cream, es miembro del Salon de la Fama del Rock and Roll por partida triple: como miembro de The Yardbirds y de Cream y por su carrera como solista. En opinion de muchos criticos, ha sido uno de los artistas de la cultura de masas mas respetados e influyentes de todos los tiempos.? Aparece en el puesto numero 2 de la lista "Los 100 guitarristas mas grandes de todos los tiempos" de la revista Rolling Stone? y en el puesto numero 55 de su especial "Inmortales: Los 100 artistas mas grandes de todos los tiempos".? Ademas, en 2005 la revista Guitar World incluyo cinco de sus canciones entre los mejores solos de guitarra de todos los tiempos. Su estilo musical ha sufrido cambios diversos a lo largo de su carrera, pero sus raices siempre han estado profundamente ligadas con el blues. Es reconocido como un innovador en varias etapas de su carrera.');
insert into i72lumav.artistas (id_artista, nombre, ranking, descripcion) values (3, 'Amy Winehouse', 4, 'Amy Jade Winehouse fue una cantante y compositora britanica, conocida por interpretar diversos generos musicales, entre los que destacan el jazz, el rhythm and blues, el soul, el ska. Asimismo, se la conoce por ser contralto, registro vocal que fue descrito como -acusticamente poderoso- y capaz de expresar -sus emociones profundamente-. En 2003 lanzo su album debut Frank, que fue un exito comercial en su pais natal, y llego a ser nominado a los Premios Mercury. Su segundo album de estudio, Back to Black, fue publicado en 2006. Por este disco la cantante consiguio seis nominaciones a los Premios Grammy, de las cuales gano cinco: Cancion del ano, Grabacion del ano y Mejor artista nueva, entre otras. Este hecho la condujo a igualar el record de galardones obtenidos en una noche por un artista (logrado antes por Lauryn Hill, Norah Jones, Alicia Keys y Beyonce), ademas de ser la primera artista britanica ganadora de cinco Grammys en una noche. La popularidad alcanzada acaparo la atencion de los medios, que comenzaron a interesarse e inmiscuirse en su agitada vida personal.???');
insert into i72lumav.artistas (id_artista, nombre, ranking, descripcion) values (4, 'Van Morrison', 7, null);
insert into i72lumav.artistas (id_artista, nombre, ranking, descripcion) values (5, 'Mark Knopfler', 2, 'Mark Freuder Knopfler es un musico de sesion, guitarrista, productor discografico, cantante y compositor escoces. Antes de su carrera como musico, trabajo de periodista y dio clases en la universidad. Principalmente conocido como fundador, guitarrista y cantante de la banda Dire Straits y su singular estilo con la guitarra sin pua, esta considerado como uno de los musicos mas importantes de la historia del rock. Tambien ha tocado en otras bandas, para otros artistas, ha participado en infinidad de discos de Phil Lynott, Solo in Soho y The Philip Lynott Album y ha realizado proyectos en solitario. Ademas, ha compuesto musica para varias peliculas, incluyendo Local Hero, Comfort and Joy, Cal, La princesa prometida, Last exit to Brooklyn, Wag the Dog, Metroland y A shot at glory, y para otros cantantes como Tina Turner, Private Dancer. Actualmente lleva una carrera en solitario, con un estilo un tanto diferente al que creo con Dire Straits, basado en un estilo propio, mezcla de diversas fuentes como el blues, el rock y el folk. La revista Rolling Stone lo situa en el puesto 44 de la lista de los 100 guitarristas mas grandes de todos los tiempos.?');
insert into i72lumav.artistas (id_artista, nombre, ranking, descripcion) values (6, 'Bruno Mars', 5, null);
insert into i72lumav.artistas (id_artista, nombre, ranking, descripcion) values (7, 'Jack Broadbent', 6, null);
insert into i72lumav.artistas_albumes (id_artista, id_album) values (1, 1);
insert into i72lumav.artistas_albumes (id_artista, id_album) values (1, 2);
insert into i72lumav.artistas_albumes (id_artista, id_album) values (1, 3);
insert into i72lumav.artistas_albumes (id_artista, id_album) values (1, 5);
insert into i72lumav.artistas_albumes (id_artista, id_album) values (1, 7);
insert into i72lumav.artistas_albumes (id_artista, id_album) values (1, 8);
insert into i72lumav.artistas_albumes (id_artista, id_album) values (2, 4);
insert into i72lumav.artistas_albumes (id_artista, id_album) values (2, 6);
insert into i72lumav.artistas_albumes (id_artista, id_album) values (2, 10);
insert into i72lumav.artistas_albumes (id_artista, id_album) values (2, 16);
insert into i72lumav.artistas_albumes (id_artista, id_album) values (3, 9);
insert into i72lumav.artistas_albumes (id_artista, id_album) values (4, 10);
insert into i72lumav.artistas_albumes (id_artista, id_album) values (5, 11);
insert into i72lumav.artistas_albumes (id_artista, id_album) values (5, 12);
insert into i72lumav.artistas_albumes (id_artista, id_album) values (5, 14);
insert into i72lumav.artistas_albumes (id_artista, id_album) values (6, 13);
insert into i72lumav.artistas_albumes (id_artista, id_album) values (7, 15);
insert into i72lumav.estilos_musicales (nombre_estilo) values ('Musica clasica');
insert into i72lumav.estilos_musicales (nombre_estilo) values ('Blues');
insert into i72lumav.estilos_musicales (nombre_estilo) values ('Jazz');
insert into i72lumav.estilos_musicales (nombre_estilo) values ('Rhythm and Blues');
insert into i72lumav.estilos_musicales (nombre_estilo) values ('Rock and Roll');
insert into i72lumav.estilos_musicales (nombre_estilo) values ('Gospel');
insert into i72lumav.estilos_musicales (nombre_estilo) values ('Soul');
insert into i72lumav.estilos_musicales (nombre_estilo) values ('Rock');
insert into i72lumav.estilos_musicales (nombre_estilo) values ('Metal');
insert into i72lumav.estilos_musicales (nombre_estilo) values ('Hardcore punk');
insert into i72lumav.estilos_musicales (nombre_estilo) values ('Country');
insert into i72lumav.estilos_musicales (nombre_estilo) values ('Funk');
insert into i72lumav.estilos_musicales (nombre_estilo) values ('Disco');
insert into i72lumav.estilos_musicales (nombre_estilo) values ('House');
insert into i72lumav.estilos_musicales (nombre_estilo) values ('Techno');
insert into i72lumav.estilos_musicales (nombre_estilo) values ('Pop');
insert into i72lumav.estilos_musicales (nombre_estilo) values ('Ska');
insert into i72lumav.estilos_musicales (nombre_estilo) values ('Reggae');
insert into i72lumav.estilos_musicales (nombre_estilo) values ('Drum and Bass');
insert into i72lumav.estilos_musicales (nombre_estilo) values ('Garage');
insert into i72lumav.estilos_musicales (nombre_estilo) values ('Flamenco');
insert into i72lumav.estilos_musicales (nombre_estilo) values ('Salsa');
insert into i72lumav.estilos_musicales (nombre_estilo) values ('Hip Hop');
insert into i72lumav.estilos_musicales (nombre_estilo) values ('Reggaeton');
insert into i72lumav.estilos_musicales (nombre_estilo) values ('Intrumental');
insert into i72lumav.estilos_musicales (nombre_estilo) values ('Banda sonora');
insert into i72lumav.estilos_musicales (nombre_estilo) values ('Vocal');
insert into i72lumav.artistas_em (id_artista, nombre_estilo) values (1, 'Rock');
insert into i72lumav.artistas_em (id_artista, nombre_estilo) values (1, 'Blues');
insert into i72lumav.artistas_em (id_artista, nombre_estilo) values (1, 'Country');
insert into i72lumav.artistas_em (id_artista, nombre_estilo) values (2, 'Rock');
insert into i72lumav.artistas_em (id_artista, nombre_estilo) values (2, 'Blues');
insert into i72lumav.artistas_em (id_artista, nombre_estilo) values (3, 'Soul');
insert into i72lumav.artistas_em (id_artista, nombre_estilo) values (3, 'Rhythm and Blues');
insert into i72lumav.artistas_em (id_artista, nombre_estilo) values (4, 'Rock');
insert into i72lumav.artistas_em (id_artista, nombre_estilo) values (4, 'Jazz');
insert into i72lumav.artistas_em (id_artista, nombre_estilo) values (5, 'Rock');
insert into i72lumav.artistas_em (id_artista, nombre_estilo) values (5, 'Blues');
insert into i72lumav.artistas_em (id_artista, nombre_estilo) values (5, 'Country');
insert into i72lumav.artistas_em (id_artista, nombre_estilo) values (5, 'Intrumental');
insert into i72lumav.artistas_em (id_artista, nombre_estilo) values (5, 'Banda sonora');
insert into i72lumav.artistas_em (id_artista, nombre_estilo) values (6, 'Pop');
insert into i72lumav.artistas_em (id_artista, nombre_estilo) values (6, 'Rhythm and Blues');
insert into i72lumav.artistas_em (id_artista, nombre_estilo) values (6, 'Reggae');
insert into i72lumav.artistas_em (id_artista, nombre_estilo) values (6, 'Funk');
insert into i72lumav.artistas_em (id_artista, nombre_estilo) values (6, 'Soul');
insert into i72lumav.artistas_em (id_artista, nombre_estilo) values (6, 'Hip Hop');
insert into i72lumav.artistas_em (id_artista, nombre_estilo) values (6, 'Rock');
insert into i72lumav.artistas_em (id_artista, nombre_estilo) values (7, 'Rock');
insert into i72lumav.artistas_em (id_artista, nombre_estilo) values (7, 'Blues');
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (1, 1, 1, 'Down To The Waterline', '4 minutos y 1 segundo', 30125093);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (2, 1, 2, 'Water Of Love', '5 minutos y 25 segundos', 24236374);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (3, 1, 3, 'Setting Me Up', '3 minutos y 18 segundos', 8609406);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (4, 1, 4, 'Six Blade Knife', '4 minutos y 12 segundos', 23956361);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (5, 1, 5, 'Southbound Again', '2 minutos y 59 segundos', 9413549);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (6, 1, 6, 'Sultans Of Swing', '5 minutos y 48 segundos', 711186594);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (7, 1, 7, 'In The Gallery', '6 minutos y 15 segundos', 10522557);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (8, 1, 8, 'Wild West End', '4 minutos y 41 segundos', 17421562);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (9, 1, 9, 'Lions', '5 minutos y 3 segundos', 11865750);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (10, 2, 1, 'Once Upon A Time In The West', '5 minutos y 24 segundo', 23125922);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (11, 2, 2, 'News', '4 minutos y 13 segundos', 11889754);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (12, 2, 3, 'Where Do You Think You re Going', '3 minutos y 49 segundos', 16666273);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (13, 2, 4, 'Communique', '5 minutos y 48 segundos', 10359843);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (14, 2, 5, 'Lady Writer', '3 minutos y 44 segundos', 51094543);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (15, 2, 6, 'Angel Of Mercy', '4 minutos y 34 segundos', 4826264);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (16, 2, 7, 'Portobello Belle', '4 minutos y 29 segundos', 5757198);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (17, 2, 8, 'Single Handed Sailor', '4 minutos y 42 segundos', 10312311);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (18, 2, 9, 'Follow Me Home', '5 minutos y 50 segundos', 4447326);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (19, 3, 1, 'Tunnel Of Love', '8 minutos y 9 segundos', 51871409);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (20, 3, 2, 'Romeo And Juliet', '6 minutos', 171942699);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (21, 3, 3, 'Skateaway', '6 minutos y 37 segundos', 13769495);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (22, 3, 4, 'Expresso Love', '5 minutos y 11 segundos', 12560376);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (23, 3, 5, 'Hand In Hand', '4 minutos y 47 segundos', 8534945);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (24, 3, 6, 'Solid Rock', '3 minutos y 25 segundos', 8615371);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (25, 3, 7, 'Les Boys', '4 minutos y 8 segundo', 3071279);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (26, 4, 1, 'Pretending', '4 minutos y 43 segundos', 6095144);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (27, 4, 2, 'Anything for Your Love', '4 minutos y 10 segundos', 713319);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (28, 4, 3, 'Bad Love', '5 minutos y 8 segundos', 9359698);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (29, 4, 4, 'Running On Faith', '5 minutos y 33 segundos', 1177302);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (30, 4, 5, 'Hard Times', '3 minutos y 14 segundos', 720232);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (31, 4, 6, 'Hound Dog', '2 minutos y 27 segundos', 565239);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (32, 4, 7, 'No Alibis', '5 minutos y 38 segundos', 2791945);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (33, 4, 8, 'Run So Far', '4 minutos y 7 segundos', 501242);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (34, 4, 9, 'Old Love', '6 minutos y 24 segundos', 2922625);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (35, 4, 10, 'Breaking Point', '3 minutos y 57 segundos', 506545);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (36, 4, 11, 'Lead Me On', '5 minutos y 52 segundos', 638281);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (37, 4, 12, 'Before You Accuse Me', '3 mminutos y 57 segundos', 8725966);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (38, 5, 1, 'Twisting By The Pool', '3 minutos y 30 segundos', 12287721);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (39, 5, 2, 'Two Young Lovers', '3 minutos y 22 segundos', 1232270);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (40, 5, 3, 'If I Had You', '4 minutos y 15 segundos', 1414416);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (41, 5, 4, 'Badges, Posters, Stickers, T-shirst', '4 minutos y 57 segundos', 1530030);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (42, 6, 1, 'It s In The Way That You Use It', '4 minutos y 11 segundos', 10857832);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (43, 6, 2, 'Run', '3 minutos y 39 segundos', 436763);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (44, 6, 3, 'Tearing Us Apart', '4 minutos y 15 segundos', 649151);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (45, 6, 4, 'Bad Influence', '5 minutos y 9 segundos', 344876);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (46, 6, 5, 'Walk Away', '3 minutos y 52 segundos', 313069);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (47, 6, 6, 'Hung Up On Your Love', '3 minutos y 53 segundos', 272940);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (48, 6, 7, 'Take a Chance', '4 minutos y 54 segundos', 265659);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (49, 6, 8, 'Hold On', '4 minutos y 56 segundos', 250515);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (50, 6, 9, 'Miss You', '5 minutos y 6 segundos', 995821);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (51, 6, 10, 'Holy Mother', '4 minutos y 55 segundos', 731500);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (52, 6, 11, 'Behind The Mask', '4 minutos y 47 segundos', 3980821);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (53, 6, 12, 'Grand Illusion', '6 minutos y 23 segundos', 233708);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (54, 7, 1, 'So Far Away', '5 minutos y 6 segundos', 81271011);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (55, 7, 2, 'Money For Nothing', '8 minutos y 25 segundos', 298137895);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (56, 7, 3, 'Walk Of Life', '4 minutos y 8 segundos', 369306358);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (57, 7, 4, 'Your Latest Trick', '6 minutos y 29 segundos', 78144436);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (58, 7, 5, 'Why Worry', '8 minutos y 24 segundos', 41400709);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (59, 7, 6, 'Ride Across The River', '6 minutos y 58 segundos', 13473676);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (60, 7, 7, 'The Man s Too Strong', '4 minutos y 38 segundos', 15393836);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (61, 7, 8, 'One World', '3 minutos y 37 segundos', 10318400);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (62, 7, 9, 'Brothers In Arms', '7 minutos', 194263135);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (63, 8, 1, 'Calling Elvis', '6 minutos y 24 segundos', 20336871);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (64, 8, 2, 'On Every Street', '5 minutos y 1 segundo', 24779774);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (65, 8, 3, 'When It Comes To You', '4 minutos y 59 segundos', 11008708);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (66, 8, 4, 'Fade To Black', '3 minutos y 47 segundos', 6336415);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (67, 8, 5, 'The Bug', '4 minutos y 14 segundos', 7332692);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (68, 8, 6, 'You And Your Friend', '5 minutos y 57 segundos', 15385342);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (69, 8, 7, 'Heavy Fuel', '5 minutos y 9 segundos', 14124823);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (70, 8, 8, 'Iron Hand', '3 minutos y 8 segundos', 5537525);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (71, 8, 9, 'Ticket To Heaven', '4 minutos y 24 segundos', 15492458);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (72, 8, 10, 'My Parties', '5 minutos y 30 segundos', 4286597);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (73, 8, 11, 'Planet Of New Orleans', '7 minutos y 45 segundos', 4011764);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (74, 8, 12, 'How Long', '3 minutos y 49 segundos', 4487409);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (75, 9, 1, 'Rehab', '3 minutos y 34 segundos', 347369514);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (76, 9, 2, 'You Know I m No Good', '4 minutos y 17 segundos', 306343117);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (77, 9, 3, 'Me and Mr Jones', '2 minutos y 33 segundos', 109893286);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (78, 9, 4, 'Just Friends', '3 minutos y 13 segundos', 40725856);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (79, 9, 5, 'Back To Black', '4 minutos y 1 segundo', 515708737);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (80, 9, 6, 'Love Is A Losing Game', '2 minutos y 35 segundos', 143344337);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (81, 9, 7, 'Tears Dry On Their Own', '3 minutos y 6 segundos', 248425442);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (82, 9, 8, 'Wake Up Alone', '3 minutos y 42 segundos', 66906873);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (83, 9, 9, 'Some Unholy War', '2 minutos y 22 segundos', 60239216);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (84, 9, 10, 'He Can Only Hold Her', '2 minutos y 46 segundos', 70113830);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (85, 9, 11, 'Addicted', '2 minutos y 45 segundos', 40816870);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (86, 10, 1, 'Stand And Deliver', '4 minutos y 32 segundos', 1111695);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (87, 11, 1, 'The Trawlerman s Song', '5 minutos', 7211074);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (88, 11, 2, 'Back To Tupelo', '4 minutos y 31 segundos', 318821);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (89, 11, 3, 'Song For Sonny Liston', '5 minutos y 28 segundos', 340493);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (90, 11, 4, 'Boom, Like That', '4 minutos y 34 segundos', 255425);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (91, 11, 5, 'Donegan s Gone', '2 minutos y 56 segundos', 197181);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (92, 11, 6, 'Stand Up Guy', '4 minutos y 30 segundos', 191327);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (93, 12, 1, 'Redbud Tree', '3 minutos y 18 segundos', 9350876);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (94, 13, 1, '24K Magic', '3 minutos y 25 segundos', 1040994214);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (95, 14, 1, 'Why Aye Man', '6 minutos y 12 segundos', 5243808);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (96, 14, 2, 'Small Potatoes', '3 minutos y 10 segundos', 82825);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (97, 14, 3, 'So Far Away', '4 minutos y 38 segundos', 128996);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (98, 14, 4, 'Speedway At Nazareth', '7 minutos y 54 segundos', 141172);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (99, 15, 1, 'Slide it in', '16 minutos y 56 segundos', 1338117);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (100, 15, 2, 'She said', '2 minutos y 2 segundos', 143943);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (101, 15, 3, 'Heat of the night', '3 minutos y 12 segundos', 73946);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (102, 15, 4, 'What if I only had one?', '2 minutos y 23 segundos', 79158);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (103, 15, 5, 'Wait another day', '40 segundos', 47955);
insert into i72lumav.canciones (id_cancion, id_album, indice, titulo, duracion, reproducciones) values (104, 16, 1, 'I Shot The Sheriff', '6 minutos y 51 segundos', 3371794);
insert into i72lumav.usuarios (email, contrasena) values ('admin@bbddaa.com', 'admin');
insert into i72lumav.usuarios (email, contrasena) values ('lixepasuha-1174@bbddaa.com', 'JVSSth$eLt$$');
insert into i72lumav.usuarios (email, contrasena) values ('brixatroudeppa-2336@bbddaa.com', 'me2P$4vHglV$');
insert into i72lumav.usuarios (email, contrasena) values ('ceiffiwafreza-6533@bbddaa.com', 'oQeArNw@0Lfe');
insert into i72lumav.usuarios (email, contrasena) values ('prauvegagriffei-4787@bbddaa.com', '3RoUusqEm2^u');
insert into i72lumav.usuarios (email, contrasena) values ('goibriliquousoi-6568@bbddaa.com', '^VUYmznbs6fz');
insert into i72lumav.usuarios (email, contrasena) values ('higuquauyeyou-7236@bbddaa.com', 'G*Vk1Pz0Ap%4');
insert into i72lumav.usuarios (email, contrasena) values ('gruleixatreija-8928@bbddaa.com', 'hA*xDcyJVMca');
insert into i72lumav.canciones_playlist (id_cancion, email, titulo, indice) values (1.0, 'lixepasuha-1174@bbddaa.com', 'Playlist 1', 1.0);
insert into i72lumav.canciones_playlist (id_cancion, email, titulo, indice) values (28.0, 'lixepasuha-1174@bbddaa.com', 'Playlist 1', 2.0);
insert into i72lumav.canciones_playlist (id_cancion, email, titulo, indice) values (50.0, 'lixepasuha-1174@bbddaa.com', 'Playlist 1', 3.0);
insert into i72lumav.canciones_playlist (id_cancion, email, titulo, indice) values (87.0, 'lixepasuha-1174@bbddaa.com', 'Playlist 1', 4.0);
insert into i72lumav.canciones_playlist (id_cancion, email, titulo, indice) values (95.0, 'lixepasuha-1174@bbddaa.com', 'Playlist 1', 5.0);
insert into i72lumav.canciones_playlist (id_cancion, email, titulo, indice) values (104.0, 'lixepasuha-1174@bbddaa.com', 'Playlist 1', 6.0);
insert into i72lumav.canciones_playlist (id_cancion, email, titulo, indice) values (84.0, 'lixepasuha-1174@bbddaa.com', 'Playlist 1', 7.0);
insert into i72lumav.canciones_playlist (id_cancion, email, titulo, indice) values (2.0, 'ceiffiwafreza-6533@bbddaa.com', 'Playlist 1', 1.0);
insert into i72lumav.canciones_playlist (id_cancion, email, titulo, indice) values (11.0, 'ceiffiwafreza-6533@bbddaa.com', 'Playlist 1', 2.0);
insert into i72lumav.canciones_playlist (id_cancion, email, titulo, indice) values (20.0, 'ceiffiwafreza-6533@bbddaa.com', 'Playlist 1', 3.0);
insert into i72lumav.canciones_playlist (id_cancion, email, titulo, indice) values (27.0, 'ceiffiwafreza-6533@bbddaa.com', 'Playlist 1', 4.0);
insert into i72lumav.canciones_playlist (id_cancion, email, titulo, indice) values (39.0, 'ceiffiwafreza-6533@bbddaa.com', 'Playlist 1', 5.0);
insert into i72lumav.canciones_playlist (id_cancion, email, titulo, indice) values (43.0, 'ceiffiwafreza-6533@bbddaa.com', 'Playlist 1', 6.0);
insert into i72lumav.canciones_playlist (id_cancion, email, titulo, indice) values (73.0, 'higuquauyeyou-7236@bbddaa.com', 'Lista de soul, blues', 1.0);
insert into i72lumav.canciones_playlist (id_cancion, email, titulo, indice) values (75.0, 'higuquauyeyou-7236@bbddaa.com', 'Lista de soul, blues', 2.0);
insert into i72lumav.canciones_playlist (id_cancion, email, titulo, indice) values (84.0, 'higuquauyeyou-7236@bbddaa.com', 'Lista de soul, blues', 3.0);
insert into i72lumav.canciones_playlist (id_cancion, email, titulo, indice) values (99.0, 'higuquauyeyou-7236@bbddaa.com', 'Lista de soul, blues', 4.0);
insert into i72lumav.canciones_playlist (id_cancion, email, titulo, indice) values (6.0, 'admin@bbddaa.com', 'Lista de Dire Straits', 1.0);
insert into i72lumav.canciones_playlist (id_cancion, email, titulo, indice) values (55.0, 'admin@bbddaa.com', 'Lista de Dire Straits', 2.0);
insert into i72lumav.canciones_playlist (id_cancion, email, titulo, indice) values (69.0, 'admin@bbddaa.com', 'Lista de Dire Straits', 3.0);
insert into i72lumav.canciones_playlist (id_cancion, email, titulo, indice) values (10.0, 'admin@bbddaa.com', 'Lista de Dire Straits', 4.0);
insert into i72lumav.canciones_playlist (id_cancion, email, titulo, indice) values (24.0, 'admin@bbddaa.com', 'Lista de Dire Straits', 5.0);
insert into i72lumav.canciones_playlist (id_cancion, email, titulo, indice) values (104.0, 'gruleixatreija-8928@bbddaa.com', 'Canciones aleatorias', 1.0);
insert into i72lumav.canciones_playlist (id_cancion, email, titulo, indice) values (103.0, 'gruleixatreija-8928@bbddaa.com', 'Canciones aleatorias', 2.0);
insert into i72lumav.canciones_playlist (id_cancion, email, titulo, indice) values (102.0, 'gruleixatreija-8928@bbddaa.com', 'Canciones aleatorias', 3.0);
insert into i72lumav.canciones_playlist (id_cancion, email, titulo, indice) values (101.0, 'gruleixatreija-8928@bbddaa.com', 'Canciones aleatorias', 4.0);
insert into i72lumav.canciones_playlist (id_cancion, email, titulo, indice) values (100.0, 'gruleixatreija-8928@bbddaa.com', 'Canciones aleatorias', 5.0);
insert into i72lumav.canciones_playlist (id_cancion, email, titulo, indice) values (99.0, 'gruleixatreija-8928@bbddaa.com', 'Canciones aleatorias', 6.0);
insert into i72lumav.canciones_playlist (id_cancion, email, titulo, indice) values (nan, 'prauvegagriffei-4787@bbddaa.com', 'Nueva lista de reproduccion', null);
insert into i72lumav.nfts (token_id, direccion, estandar, blockchain, email, id_album) values (1, '8A875218EF33A3FFCABE9B26FAAC51C1F60A31052DCE1332C57B09E4009B0EB5', 'ERC-721', 'ethereum', 'admin@bbddaa.com', 7);
insert into i72lumav.nfts (token_id, direccion, estandar, blockchain, email, id_album) values (2, '9CBB7192AB86163AC7E9735188AF7E4D9E822793DDD959BA7FE42E85CEF89103', 'ERC-721', 'ethereum', 'admin@bbddaa.com', 7);
insert into i72lumav.nfts (token_id, direccion, estandar, blockchain, email, id_album) values (3, 'BD4327CD0C8531785658EBCF87664D51CD76BB2159AA27FDD059057EAC2EBD6E', 'ERC-721', 'ethereum', 'admin@bbddaa.com', 7);
insert into i72lumav.nfts (token_id, direccion, estandar, blockchain, email, id_album) values (4, 'B64CA1B9E3210F8273036BC87450F78871B202C4DAF9A561AF0614401DBA66E2', 'ERC-721', 'ethereum', 'admin@bbddaa.com', 7);
insert into i72lumav.nfts (token_id, direccion, estandar, blockchain, email, id_album) values (5, 'CE4BB5E0E112826E4F9E21B396F60049D6E217B75DA08A6AEE06054040C7C952', 'ERC-721', 'ethereum', 'admin@bbddaa.com', 7);
insert into i72lumav.nfts (token_id, direccion, estandar, blockchain, email, id_album) values (1, '38708F733FC00E4EF5166C57F4B39E57FCB023DAF74E3F002DEA87ED6E8B3BAC', 'metaplex', 'solana', 'prauvegagriffei-4787@bbddaa.com', 13);
insert into i72lumav.nfts (token_id, direccion, estandar, blockchain, email, id_album) values (2, '45CA9A55A36DFF64E945FB251735C73D641690AA5F8CA9FE764F0A178FD4DB75', 'metaplex', 'solana', 'prauvegagriffei-4787@bbddaa.com', 13);
insert into i72lumav.nfts (token_id, direccion, estandar, blockchain, email, id_album) values (3, '5D387DF7BF87BE9BED9259020E1A7C5BA31558569E2C50ED285FE9BDB556F766', 'metaplex', 'solana', 'prauvegagriffei-4787@bbddaa.com', 13);
insert into i72lumav.nfts (token_id, direccion, estandar, blockchain, email, id_album) values (4, '8A4EB5F952D08AD796017FBBD217203F57C9E0ADC6636A76DBA2F01FF6C67CA0', 'metaplex', 'solana', 'prauvegagriffei-4787@bbddaa.com', 13);
insert into i72lumav.nfts (token_id, direccion, estandar, blockchain, email, id_album) values (5, '492FEB201BF2196C4EBE8E0C223931386805E14FACDB9EB9F9DF488C1763A0A5', 'metaplex', 'solana', 'prauvegagriffei-4787@bbddaa.com', 13);
insert into i72lumav.nfts (token_id, direccion, estandar, blockchain, email, id_album) values (1, '09583F737139EC577D156B9ABA0451FA1C3AF23A3D7DE53E5C6C3003890904DA', 'BEP-721', 'binance smart chain', 'gruleixatreija-8928@bbddaa.com', 15);
insert into i72lumav.nfts (token_id, direccion, estandar, blockchain, email, id_album) values (2, '090A9D59B51633E466D3783361484424205BB31983DC0850D48F6C60530380E1', 'BEP-721', 'binance smart chain', 'gruleixatreija-8928@bbddaa.com', 15);
insert into i72lumav.nfts (token_id, direccion, estandar, blockchain, email, id_album) values (3, '6B3FA89B18250E3C08071A662949153B72A5879220708E718262EEBD1E812F8B', 'BEP-721', 'binance smart chain', 'gruleixatreija-8928@bbddaa.com', 15);
insert into i72lumav.nfts (token_id, direccion, estandar, blockchain, email, id_album) values (4, '8B11EFE3ECDF5B8849E0F782E0331EC9AE68325C2CBCE646D6A7138F33667493', 'BEP-721', 'binance smart chain', 'gruleixatreija-8928@bbddaa.com', 15);
insert into i72lumav.nfts (token_id, direccion, estandar, blockchain, email, id_album) values (5, '1AE8C01064590B38139F53F5EC40E45C34980FEEEDB54B5520EE0451FB326CA4', 'BEP-721', 'binance smart chain', 'gruleixatreija-8928@bbddaa.com', 15);
insert into i72lumav.playlist (email, titulo, duracion, n_canciones, descripcion) values ('lixepasuha-1174@bbddaa.com', 'Playlist 1', '35 minutos', 7, 'Mi primera lista.');
insert into i72lumav.playlist (email, titulo, duracion, n_canciones, descripcion) values ('ceiffiwafreza-6533@bbddaa.com', 'Playlist 1', '25 minutos', 6, 'Lista de reproduccion numero 1.');
insert into i72lumav.playlist (email, titulo, duracion, n_canciones, descripcion) values ('higuquauyeyou-7236@bbddaa.com', 'Lista de soul, blues', '29 minutos', 4, 'Un poco de soul y blues.');
insert into i72lumav.playlist (email, titulo, duracion, n_canciones, descripcion) values ('admin@bbddaa.com', 'Lista de Dire Straits', '26 minutos', 5, 'Lista de 5 temas de Dire Straits.');
insert into i72lumav.playlist (email, titulo, duracion, n_canciones, descripcion) values ('gruleixatreija-8928@bbddaa.com', 'Canciones aleatorias', '30 minutos', 6, 'Mis 6 canciones favoritas.');
insert into i72lumav.playlist (email, titulo, duracion, n_canciones, descripcion) values ('prauvegagriffei-4787@bbddaa.com', 'Nueva lista de reproduccion', '0 minutos', 0, null);
